### ISSUE TITLE
TypeError while HTML email sending is successful

### ISSUE THREAD

**Issue by fcoufour** [bcomeau/parse-server-mailgun-adapter-template#10]
When passwordResetBodyHTML is set, the option is used and the HTML email sent is well received but there is an error in the logs:

```
0|parse-se | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|parse-se | TypeError: Cannot read property 'catch' of undefined
0|parse-se |     at Promise (/home/parse/node_modules/parse-server-mailgun-adapter-template/index.js:118:11)
0|parse-se |     at Object.sendPasswordResetEmail (/home/parse/node_modules/parse-server-mailgun-adapter-template/index.js:103:14)
0|parse-se |     at /usr/lib/node_modules/parse-server/lib/Controllers/UserController.js:194:26
0|parse-se |     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

It seems to be related to the catch closure:

```
return new Promise((resolve, reject) => {
	mail.build((mailBuildError, message) => {
  if(mailBuildError){
    return reject(mailBuildError);
  }
  var dataToSend = {
    to: getRecipient(options.user),
    message: message.toString('ascii')
  };
  mailgun.messages().sendMime(dataToSend, (err, body) => {
    if (err) {
      return reject(err);
    }
    resolve(body);
  });
}).catch(err => {
  reject(err);
});
```

Has anyone experienced the same thing?

**Comment by fcoufour** [comment]
There are two issues in one.

`You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection`

This is because sendPasswordResetEmail returns a Promise but the rejection is never catched by Parse Server itself.

`TypeError: Cannot read property 'catch' of undefined`

mail.build method doesn't return a Promise so there is nothing to catch by the catch method.

@bcomeau Hi! Maybe, the intention was to catch the error locally?

**Comment by cal8891** [comment]
I am getting the same error , the email was delivered as well like your case

`0|splitsie | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|splitsie | TypeError: Cannot read property 'catch' of undefined
0|splitsie |     at Promise (/opt/splitsiesd/node_modules/parse-server-mailgun-adapter-template/index.js:118:11)
0|splitsie |     at Object.sendPasswordResetEmail (/opt/splitsiesd/node_modules/parse-server-mailgun-adapter-template/index.js:103:14)
0|splitsie |     at /opt/splitsiesd/node_modules/parse-server/lib/Controllers/UserController.js:213:26
0|splitsie |     at process._tickDomainCallback (internal/process/next_tick.js:129:7)`


my config:
`emailAdapter: {
    module: 'parse-server-mailgun-adapter-template',
    options: {
      displayName: 'Splitsies ﻖﻃﺓ',
      fromAddress: 'from@address,
      domain: 'domain',
      apiKey: 'key**',
      verificationSubject: 'Please verify your e-mail for %appname% ﺕﺄﻜﻳﺩ ﺎﻠﺘﺴﺠﻴﻟ',
      verificationBody: 'Hi,\n\nYou are being asked to confirm the e-mail address %email% with %appname%\n\nClick here to confirm it:\n%link%',
      verificationBodyHTML: fs.readFileSync("./verifyBody.html", "utf8") ||  null,
      passwordResetSubject: 'Password Reset Request for %appname% ﺈﻋﺍﺩﺓ ﺖﻬﻴﺋﺓ ﻚﻠﻣﺓ ﺎﻠﻣﺭﻭﺭ',
      passwordResetBody: 'Hi,\n\nYou requested a password reset for %appname%.\n\nClick here to reset it:\n%link%',
      passwordResetBodyHTML: fs.readFileSync("./resetBody.html", "utf8") ||  null
    }
  }`

Does it have anything to do with the fact that my html and config contain none english characters ?
Even though I don't think it does since they are regular utf8 characters

**Comment by gavl-jaredqin** [comment]
got same issue.

**Comment by code-K** [comment]
Hi Guys!

I'm getting a related issue for the "emailVerifications" sent. The mails are sent correctly, but in the logs I can see the following error too,

`2|choo-dev | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2|choo-dev | TypeError: Cannot read property 'catch' of undefined
2|choo-dev |     at mail.build.data.from (/srv/users/serverpilot/apps/apichooappcom/public/node_modules/parse-server-mailgun-adapter-template/index.js:72:11)
2|choo-dev |     at Object.mail.build.Promise [as sendVerificationEmail] (/srv/users/serverpilot/apps/apichooappcom/public/node_modules/parse-server-mailgun-adapter-template/index.js:57:14)
2|choo-dev |     at /srv/users/serverpilot/apps/apichooappcom/public/node_modules/parse-server/lib/Controllers/UserController.js:174:26
2|choo-dev |     at process._tickDomainCallback (internal/process/next_tick.js:129:7)`

Also another question: (but I think more related to parse-server)
Overtime I re-save a user object on parse-server the verification Email will be sent out again, even if the email address of the user didn't change. So user saved with the same email as before but other fields of user updated results in a new emailVerification... Googled a lot about this already but didn't find anything...

Currently I'm trying in the beforeSave method for the User, if I can prevent this anyway... -.-

Maybe someone of you run into the same issues?

Thanks for any feedback and best regards,
Chris

**Comment by fcoufour** [comment]
Hi Chris,

I doubt the repository owner is still reading this.

Concerning your question, I have never used the email verification. Maybe, you should try to test if the same thing happens with the default simple mailgun adapter. If so, then create a new issue in the parse-server repository.

**Comment by bcomeau** [comment]
I'll be glad to review and merge a pull request that fixes this issue.
